package pipewire

KEY_NODE_GROUP :: "node.group"
VERSION_CORE :: 4
VERSION_REGISTRY :: 3
VERSION_LINK :: 3
VERSION_LINK_EVENTS :: 0
VERSION_REGISTRY_METHODS :: 0
VERSION_CORE_METHODS :: 0
VERSION_CORE_EVENTS :: 1
VERSION_NODE_METHODS :: 0
VERSION_NODE_EVENTS :: 0
VERSION_METADATA_METHODS :: 0
VERSION_METADATA_EVENTS :: 0
VERSION_PROXY_EVENTS :: 1

LINK_CHANGE_MASK_STATE :: 1 << 0
LINK_CHANGE_MASK_FORMAT :: 1 << 1
LINK_CHANGE_MASK_PROPS :: 1 << 2
LINK_CHANGE_MASK_ALL :: (1 << 3) - 1
