on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: node-lts
    steps:
      - run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN is empty"
            exit 1
          else
            echo "GH_TOKEN is set (length: ${#TOKEN})"
          fi
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v6
      - uses: https://github.com/laytan/setup-odin@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: apt-get update && apt-get install -y glslang-tools clang
      - run: make

